"""Declarative base, naming convention и общие mixin-колонки (Глава 2, ADR 0003)."""

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Детерминированные имена constraints/индексов: autogenerate и downgrade
# опираются на имена, поэтому они не должны зависеть от СУБД.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class IdMixin:
    """BIGINT GENERATED BY DEFAULT AS IDENTITY (ADR 0003)."""

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True, sort_order=-100)


class CreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, sort_order=100
    )


class TimestampMixin(CreatedAtMixin):
    """updated_at выставляет триггер БД trg_set_updated_at при любом UPDATE (ADR 0006)."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        sort_order=101,
    )
