"""Глава 2: исходная схема БД EV-ServiceDesk (ADR 0003–0005).

Autogenerate из app.models + ручные дополнения, которые autogenerate не видит:
- триггер vehicle_guard (неизменяемость VIN/владельца/модели, пробег не уменьшается);
- DROP TYPE для ENUM в downgrade.

Revision ID: 0001
Revises:
Create Date: 2026-10-08
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aggregate_type",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]{1,49}$'", name=op.f("ck_aggregate_type_code_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aggregate_type")),
        sa.UniqueConstraint("code", name=op.f("uq_aggregate_type_code")),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.Column("role", sa.Enum("client", "engineer", "admin", name="user_role"), nullable=False),
        sa.Column("telegram_id", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("pd_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pd_policy_version", sa.String(length=20), nullable=True),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_app_user_phone_e164")),
        sa.CheckConstraint(
            "role = 'client' OR password_hash IS NOT NULL", name=op.f("ck_app_user_staff_password")
        ),
        sa.CheckConstraint(
            "(pd_consent_at IS NULL) = (pd_policy_version IS NULL)",
            name=op.f("ck_app_user_pd_consent_pair"),
        ),
        sa.CheckConstraint(
            "phone IS NOT NULL OR anonymized_at IS NOT NULL",
            name=op.f("ck_app_user_phone_required"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("phone", name=op.f("uq_app_user_phone")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_app_user_telegram_id")),
    )
    op.create_table(
        "vehicle_model",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("trim", sa.String(length=100), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_model")),
        sa.UniqueConstraint(
            "brand", "model", "trim", name=op.f("uq_vehicle_model_brand_model_trim")
        ),
    )
    op.create_table(
        "firmware_release",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_model_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("released_at", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
            name=op.f("fk_firmware_release_vehicle_model_id_vehicle_model"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_release")),
        sa.UniqueConstraint(
            "id", "vehicle_model_id", name=op.f("uq_firmware_release_id_vehicle_model_id")
        ),
        sa.UniqueConstraint(
            "vehicle_model_id", "version", name=op.f("uq_firmware_release_vehicle_model_id_version")
        ),
    )
    op.create_index(
        op.f("ix_firmware_release_vehicle_model_id"),
        "firmware_release",
        ["vehicle_model_id"],
        unique=False,
    )
    op.create_table(
        "maintenance_regulation",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_model_id", sa.BigInteger(), nullable=False),
        sa.Column("aggregate_type_id", sa.BigInteger(), nullable=False),
        sa.Column("interval_km", sa.Integer(), nullable=True),
        sa.Column("interval_months", sa.Integer(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interval_km IS NOT NULL OR interval_months IS NOT NULL",
            name=op.f("ck_maintenance_regulation_interval_present"),
        ),
        sa.CheckConstraint(
            "interval_km IS NULL OR interval_km > 0",
            name=op.f("ck_maintenance_regulation_interval_km_positive"),
        ),
        sa.CheckConstraint(
            "interval_months IS NULL OR interval_months > 0",
            name=op.f("ck_maintenance_regulation_interval_months_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["aggregate_type_id"],
            ["aggregate_type.id"],
            name=op.f("fk_maintenance_regulation_aggregate_type_id_aggregate_type"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
            name=op.f("fk_maintenance_regulation_vehicle_model_id_vehicle_model"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_regulation")),
    )
    op.create_index(
        op.f("ix_maintenance_regulation_aggregate_type_id"),
        "maintenance_regulation",
        ["aggregate_type_id"],
        unique=False,
    )
    op.create_index(
        "uq_maintenance_regulation_active",
        "maintenance_regulation",
        ["vehicle_model_id", "aggregate_type_id"],
        unique=True,
        postgresql_where=sa.text("is_archived = false"),
    )
    op.create_table(
        "push_token",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_push_token_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_token")),
        sa.UniqueConstraint("token", name=op.f("uq_push_token_token")),
    )
    op.create_index(op.f("ix_push_token_user_id"), "push_token", ["user_id"], unique=False)
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_refresh_token_token_hash_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_refresh_token_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_token_token_hash")),
    )
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_table(
        "knowledge_article",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_model_id", sa.BigInteger(), nullable=True),
        sa.Column("firmware_release_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "article_type",
            sa.Enum("guide", "troubleshooting", name="kb_article_type"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(title) <> ''", name=op.f("ck_knowledge_article_title_not_blank")),
        sa.CheckConstraint(
            "firmware_release_id IS NULL OR vehicle_model_id IS NOT NULL",
            name=op.f("ck_knowledge_article_firmware_requires_model"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_knowledge_article_version_positive")),
        sa.ForeignKeyConstraint(
            ["firmware_release_id", "vehicle_model_id"],
            ["firmware_release.id", "firmware_release.vehicle_model_id"],
            name="fk_knowledge_article_firmware_same_model",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
            name=op.f("fk_knowledge_article_vehicle_model_id_vehicle_model"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_article")),
    )
    op.create_index(
        op.f("ix_knowledge_article_firmware_release_id"),
        "knowledge_article",
        ["firmware_release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_article_vehicle_model_id"),
        "knowledge_article",
        ["vehicle_model_id"],
        unique=False,
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum("firmware", "maintenance", "news", "promo", name="notification_type"),
            nullable=False,
        ),
        sa.Column("firmware_release_id", sa.BigInteger(), nullable=True),
        sa.Column("target_vehicle_model_id", sa.BigInteger(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type <> 'firmware' OR firmware_release_id IS NOT NULL",
            name=op.f("ck_notification_firmware_has_release"),
        ),
        sa.CheckConstraint(
            "firmware_release_id IS NULL OR target_vehicle_model_id IS NOT NULL",
            name=op.f("ck_notification_firmware_requires_model"),
        ),
        sa.ForeignKeyConstraint(
            ["firmware_release_id", "target_vehicle_model_id"],
            ["firmware_release.id", "firmware_release.vehicle_model_id"],
            name="fk_notification_firmware_same_model",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_vehicle_model_id"],
            ["vehicle_model.id"],
            name=op.f("fk_notification_target_vehicle_model_id_vehicle_model"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
    )
    op.create_index("ix_notification_created_at", "notification", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_notification_firmware_release_id"),
        "notification",
        ["firmware_release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_target_vehicle_model_id"),
        "notification",
        ["target_vehicle_model_id"],
        unique=False,
    )
    op.create_table(
        "vehicle",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("vehicle_model_id", sa.BigInteger(), nullable=False),
        sa.Column("vin", sa.CHAR(length=17), nullable=False),
        sa.Column("mileage", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("current_firmware_release_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("vin ~ '^[A-HJ-NPR-Z0-9]{17}$'", name=op.f("ck_vehicle_vin_format")),
        sa.CheckConstraint("mileage >= 0", name=op.f("ck_vehicle_mileage_non_negative")),
        sa.ForeignKeyConstraint(
            ["current_firmware_release_id", "vehicle_model_id"],
            ["firmware_release.id", "firmware_release.vehicle_model_id"],
            name="fk_vehicle_firmware_same_model",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_vehicle_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
            name=op.f("fk_vehicle_vehicle_model_id_vehicle_model"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle")),
    )
    op.create_index(
        op.f("ix_vehicle_current_firmware_release_id"),
        "vehicle",
        ["current_firmware_release_id"],
        unique=False,
    )
    op.create_index(op.f("ix_vehicle_user_id"), "vehicle", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_vehicle_vehicle_model_id"), "vehicle", ["vehicle_model_id"], unique=False
    )
    op.create_index(
        "uq_vehicle_vin_active",
        "vehicle",
        ["vin"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "decision_tree_node",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_root", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_escalation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(options) = 'array'", name=op.f("ck_decision_tree_node_options_is_array")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["knowledge_article.id"],
            name=op.f("fk_decision_tree_node_article_id_knowledge_article"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_tree_node")),
    )
    op.create_index(
        op.f("ix_decision_tree_node_article_id"), "decision_tree_node", ["article_id"], unique=False
    )
    op.create_index(
        "uq_decision_tree_node_root",
        "decision_tree_node",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("is_root = true"),
    )
    op.create_table(
        "notification_delivery",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("notification_id", sa.BigInteger(), nullable=False),
        sa.Column("push_token_id", sa.BigInteger(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
            name=op.f("fk_notification_delivery_notification_id_notification"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["push_token_id"],
            ["push_token.id"],
            name=op.f("fk_notification_delivery_push_token_id_push_token"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_delivery")),
        sa.UniqueConstraint(
            "notification_id",
            "push_token_id",
            name=op.f("uq_notification_delivery_notification_id_push_token_id"),
        ),
    )
    op.create_index(
        op.f("ix_notification_delivery_push_token_id"),
        "notification_delivery",
        ["push_token_id"],
        unique=False,
    )
    op.create_table(
        "notification_recipient",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("notification_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
            name=op.f("fk_notification_recipient_notification_id_notification"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_notification_recipient_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_recipient")),
        sa.UniqueConstraint(
            "notification_id",
            "user_id",
            name=op.f("uq_notification_recipient_notification_id_user_id"),
        ),
    )
    op.create_index(
        "ix_notification_recipient_user_id_created_at",
        "notification_recipient",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "vehicle_aggregate_status",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.Column("aggregate_type_id", sa.BigInteger(), nullable=False),
        sa.Column("last_replaced_at", sa.Date(), nullable=True),
        sa.Column("last_replaced_mileage", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_replaced_mileage IS NULL OR last_replaced_mileage >= 0",
            name=op.f("ck_vehicle_aggregate_status_last_replaced_mileage_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["aggregate_type_id"],
            ["aggregate_type.id"],
            name=op.f("fk_vehicle_aggregate_status_aggregate_type_id_aggregate_type"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
            name=op.f("fk_vehicle_aggregate_status_vehicle_id_vehicle"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_aggregate_status")),
        sa.UniqueConstraint(
            "vehicle_id",
            "aggregate_type_id",
            name=op.f("uq_vehicle_aggregate_status_vehicle_id_aggregate_type_id"),
        ),
    )
    op.create_index(
        op.f("ix_vehicle_aggregate_status_aggregate_type_id"),
        "vehicle_aggregate_status",
        ["aggregate_type_id"],
        unique=False,
    )
    op.create_table(
        "ticket",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "navigation", "audio", "sim", "app_crash", "maintenance", name="ticket_category"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("new", "in_progress", "waiting_vendor", "resolved", name="ticket_status"),
            server_default=sa.text("'new'"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assigned_engineer_id", sa.BigInteger(), nullable=True),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("firmware_release_id", sa.BigInteger(), nullable=True),
        sa.Column("source_article_id", sa.BigInteger(), nullable=True),
        sa.Column("source_node_id", sa.BigInteger(), nullable=True),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'resolved') = (resolved_at IS NOT NULL)",
            name=op.f("ck_ticket_resolved_at_consistent"),
        ),
        sa.CheckConstraint(
            "btrim(description) <> ''", name=op.f("ck_ticket_description_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_engineer_id"],
            ["app_user.id"],
            name=op.f("fk_ticket_assigned_engineer_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["firmware_release_id"],
            ["firmware_release.id"],
            name=op.f("fk_ticket_firmware_release_id_firmware_release"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_article_id"],
            ["knowledge_article.id"],
            name=op.f("fk_ticket_source_article_id_knowledge_article"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["decision_tree_node.id"],
            name=op.f("fk_ticket_source_node_id_decision_tree_node"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
            name=op.f("fk_ticket_vehicle_id_vehicle"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket")),
    )
    op.create_index(
        op.f("ix_ticket_assigned_engineer_id"), "ticket", ["assigned_engineer_id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_firmware_release_id"), "ticket", ["firmware_release_id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_source_article_id"), "ticket", ["source_article_id"], unique=False
    )
    op.create_index(op.f("ix_ticket_source_node_id"), "ticket", ["source_node_id"], unique=False)
    op.create_index("ix_ticket_status_sla_due_at", "ticket", ["status", "sla_due_at"], unique=False)
    op.create_index(op.f("ix_ticket_vehicle_id"), "ticket", ["vehicle_id"], unique=False)
    op.create_table(
        "maintenance_record",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.Column("aggregate_type_id", sa.BigInteger(), nullable=True),
        sa.Column("performed_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("ticket_id", sa.BigInteger(), nullable=True),
        sa.Column("performed_at", sa.Date(), nullable=False),
        sa.Column("mileage_at_service", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "aggregate_type_id IS NOT NULL OR description IS NOT NULL",
            name=op.f("ck_maintenance_record_subject_present"),
        ),
        sa.CheckConstraint(
            "mileage_at_service >= 0",
            name=op.f("ck_maintenance_record_mileage_at_service_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["aggregate_type_id"],
            ["aggregate_type.id"],
            name=op.f("fk_maintenance_record_aggregate_type_id_aggregate_type"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_maintenance_record_performed_by_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
            name=op.f("fk_maintenance_record_ticket_id_ticket"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
            name=op.f("fk_maintenance_record_vehicle_id_vehicle"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_record")),
    )
    op.create_index(
        op.f("ix_maintenance_record_aggregate_type_id"),
        "maintenance_record",
        ["aggregate_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_record_performed_by_user_id"),
        "maintenance_record",
        ["performed_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_record_ticket_id"), "maintenance_record", ["ticket_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_record_vehicle_id"), "maintenance_record", ["vehicle_id"], unique=False
    )
    op.create_table(
        "ticket_message",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("ticket_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(body) <> ''", name=op.f("ck_ticket_message_body_not_blank")),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app_user.id"],
            name=op.f("fk_ticket_message_author_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
            name=op.f("fk_ticket_message_ticket_id_ticket"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_message")),
        sa.UniqueConstraint("id", "ticket_id", name=op.f("uq_ticket_message_id_ticket_id")),
    )
    op.create_index(
        op.f("ix_ticket_message_author_id"), "ticket_message", ["author_id"], unique=False
    )
    op.create_index(
        "ix_ticket_message_ticket_id_created_at",
        "ticket_message",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ticket_attachment",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("ticket_id", sa.BigInteger(), nullable=False),
        sa.Column("ticket_message_id", sa.BigInteger(), nullable=True),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.Enum("photo", "video", name="attachment_type"), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(file_type = 'photo' AND mime_type LIKE 'image/%%') OR (file_type = 'video' AND mime_type LIKE 'video/%%')",
            name=op.f("ck_ticket_attachment_mime_matches_type"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_ticket_attachment_size_positive")),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
            name=op.f("fk_ticket_attachment_ticket_id_ticket"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_message_id", "ticket_id"],
            ["ticket_message.id", "ticket_message.ticket_id"],
            name="fk_ticket_attachment_message_same_ticket",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_ticket_attachment_uploaded_by_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_attachment")),
        sa.UniqueConstraint("object_key", name=op.f("uq_ticket_attachment_object_key")),
    )
    op.create_index(
        op.f("ix_ticket_attachment_ticket_id"), "ticket_attachment", ["ticket_id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_attachment_ticket_message_id"),
        "ticket_attachment",
        ["ticket_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_attachment_uploaded_by_user_id"),
        "ticket_attachment",
        ["uploaded_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- Ручное дополнение: защита инвариантов vehicle на уровне БД (defense in depth). ---
    # Сервисный слой делает условный UPDATE ... WHERE mileage <= :new и отдаёт 409;
    # триггер не даёт нарушить инвариант в обход сервиса (SQLSTATE 23514).
    op.execute(
        """
        CREATE FUNCTION vehicle_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.vin IS DISTINCT FROM OLD.vin
               OR NEW.user_id IS DISTINCT FROM OLD.user_id
               OR NEW.vehicle_model_id IS DISTINCT FROM OLD.vehicle_model_id THEN
                RAISE EXCEPTION 'vehicle vin, user_id and vehicle_model_id are immutable'
                    USING ERRCODE = 'check_violation', CONSTRAINT = 'vehicle_identity_immutable';
            END IF;
            IF NEW.mileage < OLD.mileage THEN
                RAISE EXCEPTION 'vehicle mileage cannot decrease'
                    USING ERRCODE = 'check_violation', CONSTRAINT = 'vehicle_mileage_monotonic';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER trg_vehicle_guard BEFORE UPDATE ON vehicle "
        "FOR EACH ROW EXECUTE FUNCTION vehicle_guard()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_vehicle_guard ON vehicle")
    op.execute("DROP FUNCTION IF EXISTS vehicle_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_attachment_uploaded_by_user_id"), table_name="ticket_attachment")
    op.drop_index(op.f("ix_ticket_attachment_ticket_message_id"), table_name="ticket_attachment")
    op.drop_index(op.f("ix_ticket_attachment_ticket_id"), table_name="ticket_attachment")
    op.drop_table("ticket_attachment")
    op.drop_index("ix_ticket_message_ticket_id_created_at", table_name="ticket_message")
    op.drop_index(op.f("ix_ticket_message_author_id"), table_name="ticket_message")
    op.drop_table("ticket_message")
    op.drop_index(op.f("ix_maintenance_record_vehicle_id"), table_name="maintenance_record")
    op.drop_index(op.f("ix_maintenance_record_ticket_id"), table_name="maintenance_record")
    op.drop_index(
        op.f("ix_maintenance_record_performed_by_user_id"), table_name="maintenance_record"
    )
    op.drop_index(op.f("ix_maintenance_record_aggregate_type_id"), table_name="maintenance_record")
    op.drop_table("maintenance_record")
    op.drop_index(op.f("ix_ticket_vehicle_id"), table_name="ticket")
    op.drop_index("ix_ticket_status_sla_due_at", table_name="ticket")
    op.drop_index(op.f("ix_ticket_source_node_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_source_article_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_firmware_release_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_assigned_engineer_id"), table_name="ticket")
    op.drop_table("ticket")
    op.drop_index(
        op.f("ix_vehicle_aggregate_status_aggregate_type_id"), table_name="vehicle_aggregate_status"
    )
    op.drop_table("vehicle_aggregate_status")
    op.drop_index(
        "ix_notification_recipient_user_id_created_at", table_name="notification_recipient"
    )
    op.drop_table("notification_recipient")
    op.drop_index(
        op.f("ix_notification_delivery_push_token_id"), table_name="notification_delivery"
    )
    op.drop_table("notification_delivery")
    op.drop_index(
        "uq_decision_tree_node_root",
        table_name="decision_tree_node",
        postgresql_where=sa.text("is_root = true"),
    )
    op.drop_index(op.f("ix_decision_tree_node_article_id"), table_name="decision_tree_node")
    op.drop_table("decision_tree_node")
    op.drop_index(
        "uq_vehicle_vin_active",
        table_name="vehicle",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_vehicle_vehicle_model_id"), table_name="vehicle")
    op.drop_index(op.f("ix_vehicle_user_id"), table_name="vehicle")
    op.drop_index(op.f("ix_vehicle_current_firmware_release_id"), table_name="vehicle")
    op.drop_table("vehicle")
    op.drop_index(op.f("ix_notification_target_vehicle_model_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_firmware_release_id"), table_name="notification")
    op.drop_index("ix_notification_created_at", table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_knowledge_article_vehicle_model_id"), table_name="knowledge_article")
    op.drop_index(op.f("ix_knowledge_article_firmware_release_id"), table_name="knowledge_article")
    op.drop_table("knowledge_article")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index(op.f("ix_push_token_user_id"), table_name="push_token")
    op.drop_table("push_token")
    op.drop_index(
        "uq_maintenance_regulation_active",
        table_name="maintenance_regulation",
        postgresql_where=sa.text("is_archived = false"),
    )
    op.drop_index(
        op.f("ix_maintenance_regulation_aggregate_type_id"), table_name="maintenance_regulation"
    )
    op.drop_table("maintenance_regulation")
    op.drop_index(op.f("ix_firmware_release_vehicle_model_id"), table_name="firmware_release")
    op.drop_table("firmware_release")
    op.drop_table("vehicle_model")
    op.drop_table("app_user")
    op.drop_table("aggregate_type")
    # ### end Alembic commands ###
    # drop_table не удаляет ENUM-типы — иначе повторный upgrade упадёт.
    op.execute("DROP TYPE IF EXISTS ticket_status")
    op.execute("DROP TYPE IF EXISTS ticket_category")
    op.execute("DROP TYPE IF EXISTS attachment_type")
    op.execute("DROP TYPE IF EXISTS notification_type")
    op.execute("DROP TYPE IF EXISTS kb_article_type")
    op.execute("DROP TYPE IF EXISTS user_role")
