-- EV-ServiceDesk — DDL (PostgreSQL 16)
-- СГЕНЕРИРОВАНО из миграций Alembic: cd backend && poetry run python scripts/export_ddl.py
-- Не редактировать вручную: источник истины — backend/alembic/versions (ADR 0003).
-- Синхронность проверяет backend/tests/db/test_ddl_export.py.

BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001

CREATE TABLE aggregate_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    code VARCHAR(50) NOT NULL, 
    name VARCHAR(100) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_aggregate_type PRIMARY KEY (id), 
    CONSTRAINT ck_aggregate_type_code_format CHECK (code ~ '^[a-z][a-z0-9_]{1,49}$'), 
    CONSTRAINT uq_aggregate_type_code UNIQUE (code)
);

CREATE TYPE user_role AS ENUM ('client', 'engineer', 'admin');

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    phone VARCHAR(16), 
    role user_role NOT NULL, 
    telegram_id VARCHAR(50), 
    password_hash VARCHAR(255), 
    is_active BOOLEAN DEFAULT true NOT NULL, 
    pd_consent_at TIMESTAMP WITH TIME ZONE, 
    pd_policy_version VARCHAR(20), 
    anonymized_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_app_user PRIMARY KEY (id), 
    CONSTRAINT ck_app_user_phone_e164 CHECK (phone ~ '^\+[1-9][0-9]{7,14}$'), 
    CONSTRAINT ck_app_user_staff_password CHECK (role = 'client' OR password_hash IS NOT NULL), 
    CONSTRAINT ck_app_user_pd_consent_pair CHECK ((pd_consent_at IS NULL) = (pd_policy_version IS NULL)), 
    CONSTRAINT ck_app_user_phone_required CHECK (phone IS NOT NULL OR anonymized_at IS NOT NULL), 
    CONSTRAINT uq_app_user_phone UNIQUE (phone), 
    CONSTRAINT uq_app_user_telegram_id UNIQUE (telegram_id)
);

CREATE TABLE vehicle_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    brand VARCHAR(100) NOT NULL, 
    model VARCHAR(100) NOT NULL, 
    trim VARCHAR(100) DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_vehicle_model PRIMARY KEY (id), 
    CONSTRAINT uq_vehicle_model_brand_model_trim UNIQUE (brand, model, trim)
);

CREATE TABLE firmware_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    vehicle_model_id BIGINT NOT NULL, 
    version VARCHAR(50) NOT NULL, 
    released_at DATE NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_firmware_release PRIMARY KEY (id), 
    CONSTRAINT fk_firmware_release_vehicle_model_id_vehicle_model FOREIGN KEY(vehicle_model_id) REFERENCES vehicle_model (id) ON DELETE RESTRICT, 
    CONSTRAINT uq_firmware_release_id_vehicle_model_id UNIQUE (id, vehicle_model_id), 
    CONSTRAINT uq_firmware_release_vehicle_model_id_version UNIQUE (vehicle_model_id, version)
);

CREATE INDEX ix_firmware_release_vehicle_model_id ON firmware_release (vehicle_model_id);

CREATE TABLE maintenance_regulation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    vehicle_model_id BIGINT NOT NULL, 
    aggregate_type_id BIGINT NOT NULL, 
    interval_km INTEGER, 
    interval_months INTEGER, 
    is_archived BOOLEAN DEFAULT false NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_maintenance_regulation PRIMARY KEY (id), 
    CONSTRAINT ck_maintenance_regulation_interval_present CHECK (interval_km IS NOT NULL OR interval_months IS NOT NULL), 
    CONSTRAINT ck_maintenance_regulation_interval_km_positive CHECK (interval_km IS NULL OR interval_km > 0), 
    CONSTRAINT ck_maintenance_regulation_interval_months_positive CHECK (interval_months IS NULL OR interval_months > 0), 
    CONSTRAINT fk_maintenance_regulation_aggregate_type_id_aggregate_type FOREIGN KEY(aggregate_type_id) REFERENCES aggregate_type (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_maintenance_regulation_vehicle_model_id_vehicle_model FOREIGN KEY(vehicle_model_id) REFERENCES vehicle_model (id) ON DELETE RESTRICT
);

CREATE INDEX ix_maintenance_regulation_aggregate_type_id ON maintenance_regulation (aggregate_type_id);

CREATE UNIQUE INDEX uq_maintenance_regulation_active ON maintenance_regulation (vehicle_model_id, aggregate_type_id) WHERE is_archived = false;

CREATE TABLE push_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    user_id BIGINT NOT NULL, 
    token VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_push_token PRIMARY KEY (id), 
    CONSTRAINT fk_push_token_user_id_app_user FOREIGN KEY(user_id) REFERENCES app_user (id) ON DELETE CASCADE, 
    CONSTRAINT uq_push_token_token UNIQUE (token)
);

CREATE INDEX ix_push_token_user_id ON push_token (user_id);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    user_id BIGINT NOT NULL, 
    token_hash VARCHAR(64) NOT NULL, 
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    revoked_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_refresh_token PRIMARY KEY (id), 
    CONSTRAINT ck_refresh_token_token_hash_sha256 CHECK (token_hash ~ '^[0-9a-f]{64}$'), 
    CONSTRAINT fk_refresh_token_user_id_app_user FOREIGN KEY(user_id) REFERENCES app_user (id) ON DELETE CASCADE, 
    CONSTRAINT uq_refresh_token_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_token_user_id ON refresh_token (user_id);

CREATE TYPE kb_article_type AS ENUM ('guide', 'troubleshooting');

CREATE TABLE knowledge_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    vehicle_model_id BIGINT, 
    firmware_release_id BIGINT, 
    article_type kb_article_type NOT NULL, 
    title VARCHAR(200) NOT NULL, 
    content TEXT DEFAULT '' NOT NULL, 
    version INTEGER DEFAULT 1 NOT NULL, 
    is_published BOOLEAN DEFAULT false NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_knowledge_article PRIMARY KEY (id), 
    CONSTRAINT ck_knowledge_article_title_not_blank CHECK (btrim(title) <> ''), 
    CONSTRAINT ck_knowledge_article_firmware_requires_model CHECK (firmware_release_id IS NULL OR vehicle_model_id IS NOT NULL), 
    CONSTRAINT ck_knowledge_article_version_positive CHECK (version >= 1), 
    CONSTRAINT fk_knowledge_article_firmware_same_model FOREIGN KEY(firmware_release_id, vehicle_model_id) REFERENCES firmware_release (id, vehicle_model_id) ON DELETE RESTRICT, 
    CONSTRAINT fk_knowledge_article_vehicle_model_id_vehicle_model FOREIGN KEY(vehicle_model_id) REFERENCES vehicle_model (id) ON DELETE RESTRICT
);

CREATE INDEX ix_knowledge_article_firmware_release_id ON knowledge_article (firmware_release_id);

CREATE INDEX ix_knowledge_article_vehicle_model_id ON knowledge_article (vehicle_model_id);

CREATE TYPE notification_type AS ENUM ('firmware', 'maintenance', 'news', 'promo');

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    type notification_type NOT NULL, 
    firmware_release_id BIGINT, 
    target_vehicle_model_id BIGINT, 
    message TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_notification PRIMARY KEY (id), 
    CONSTRAINT ck_notification_firmware_has_release CHECK (type <> 'firmware' OR firmware_release_id IS NOT NULL), 
    CONSTRAINT ck_notification_firmware_requires_model CHECK (firmware_release_id IS NULL OR target_vehicle_model_id IS NOT NULL), 
    CONSTRAINT fk_notification_firmware_same_model FOREIGN KEY(firmware_release_id, target_vehicle_model_id) REFERENCES firmware_release (id, vehicle_model_id) ON DELETE RESTRICT, 
    CONSTRAINT fk_notification_target_vehicle_model_id_vehicle_model FOREIGN KEY(target_vehicle_model_id) REFERENCES vehicle_model (id) ON DELETE RESTRICT
);

CREATE INDEX ix_notification_created_at ON notification (created_at);

CREATE INDEX ix_notification_firmware_release_id ON notification (firmware_release_id);

CREATE INDEX ix_notification_target_vehicle_model_id ON notification (target_vehicle_model_id);

CREATE TABLE vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    user_id BIGINT NOT NULL, 
    vehicle_model_id BIGINT NOT NULL, 
    vin CHAR(17) NOT NULL, 
    mileage INTEGER DEFAULT 0 NOT NULL, 
    current_firmware_release_id BIGINT, 
    deleted_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_vehicle PRIMARY KEY (id), 
    CONSTRAINT ck_vehicle_vin_format CHECK (vin ~ '^[A-HJ-NPR-Z0-9]{17}$'), 
    CONSTRAINT ck_vehicle_mileage_non_negative CHECK (mileage >= 0), 
    CONSTRAINT fk_vehicle_firmware_same_model FOREIGN KEY(current_firmware_release_id, vehicle_model_id) REFERENCES firmware_release (id, vehicle_model_id) ON DELETE RESTRICT, 
    CONSTRAINT fk_vehicle_user_id_app_user FOREIGN KEY(user_id) REFERENCES app_user (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_vehicle_vehicle_model_id_vehicle_model FOREIGN KEY(vehicle_model_id) REFERENCES vehicle_model (id) ON DELETE RESTRICT
);

CREATE INDEX ix_vehicle_current_firmware_release_id ON vehicle (current_firmware_release_id);

CREATE INDEX ix_vehicle_user_id ON vehicle (user_id);

CREATE INDEX ix_vehicle_vehicle_model_id ON vehicle (vehicle_model_id);

CREATE UNIQUE INDEX uq_vehicle_vin_active ON vehicle (vin) WHERE deleted_at IS NULL;

CREATE TABLE decision_tree_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    article_id BIGINT NOT NULL, 
    question_text TEXT NOT NULL, 
    options JSONB DEFAULT '[]'::jsonb NOT NULL, 
    is_root BOOLEAN DEFAULT false NOT NULL, 
    is_escalation BOOLEAN DEFAULT false NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_decision_tree_node PRIMARY KEY (id), 
    CONSTRAINT ck_decision_tree_node_options_is_array CHECK (jsonb_typeof(options) = 'array'), 
    CONSTRAINT fk_decision_tree_node_article_id_knowledge_article FOREIGN KEY(article_id) REFERENCES knowledge_article (id) ON DELETE CASCADE
);

CREATE INDEX ix_decision_tree_node_article_id ON decision_tree_node (article_id);

CREATE UNIQUE INDEX uq_decision_tree_node_root ON decision_tree_node (article_id) WHERE is_root = true;

CREATE TABLE notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    notification_id BIGINT NOT NULL, 
    push_token_id BIGINT NOT NULL, 
    delivered_at TIMESTAMP WITH TIME ZONE, 
    opened_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_notification_delivery PRIMARY KEY (id), 
    CONSTRAINT fk_notification_delivery_notification_id_notification FOREIGN KEY(notification_id) REFERENCES notification (id) ON DELETE CASCADE, 
    CONSTRAINT fk_notification_delivery_push_token_id_push_token FOREIGN KEY(push_token_id) REFERENCES push_token (id) ON DELETE CASCADE, 
    CONSTRAINT uq_notification_delivery_notification_id_push_token_id UNIQUE (notification_id, push_token_id)
);

CREATE INDEX ix_notification_delivery_push_token_id ON notification_delivery (push_token_id);

CREATE TABLE notification_recipient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    notification_id BIGINT NOT NULL, 
    user_id BIGINT NOT NULL, 
    read_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_notification_recipient PRIMARY KEY (id), 
    CONSTRAINT fk_notification_recipient_notification_id_notification FOREIGN KEY(notification_id) REFERENCES notification (id) ON DELETE CASCADE, 
    CONSTRAINT fk_notification_recipient_user_id_app_user FOREIGN KEY(user_id) REFERENCES app_user (id) ON DELETE CASCADE, 
    CONSTRAINT uq_notification_recipient_notification_id_user_id UNIQUE (notification_id, user_id)
);

CREATE INDEX ix_notification_recipient_user_id_created_at ON notification_recipient (user_id, created_at);

CREATE TABLE vehicle_aggregate_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    vehicle_id BIGINT NOT NULL, 
    aggregate_type_id BIGINT NOT NULL, 
    last_replaced_at DATE, 
    last_replaced_mileage INTEGER, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_vehicle_aggregate_status PRIMARY KEY (id), 
    CONSTRAINT ck_vehicle_aggregate_status_last_replaced_mileage_non_negative CHECK (last_replaced_mileage IS NULL OR last_replaced_mileage >= 0), 
    CONSTRAINT fk_vehicle_aggregate_status_aggregate_type_id_aggregate_type FOREIGN KEY(aggregate_type_id) REFERENCES aggregate_type (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_vehicle_aggregate_status_vehicle_id_vehicle FOREIGN KEY(vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE, 
    CONSTRAINT uq_vehicle_aggregate_status_vehicle_id_aggregate_type_id UNIQUE (vehicle_id, aggregate_type_id)
);

CREATE INDEX ix_vehicle_aggregate_status_aggregate_type_id ON vehicle_aggregate_status (aggregate_type_id);

CREATE TYPE ticket_category AS ENUM ('navigation', 'audio', 'sim', 'app_crash', 'maintenance');

CREATE TYPE ticket_status AS ENUM ('new', 'in_progress', 'waiting_vendor', 'resolved');

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    vehicle_id BIGINT NOT NULL, 
    category ticket_category NOT NULL, 
    status ticket_status DEFAULT 'new' NOT NULL, 
    description TEXT NOT NULL, 
    assigned_engineer_id BIGINT, 
    sla_due_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    firmware_release_id BIGINT, 
    source_article_id BIGINT, 
    source_node_id BIGINT, 
    first_response_at TIMESTAMP WITH TIME ZONE, 
    resolved_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_ticket PRIMARY KEY (id), 
    CONSTRAINT ck_ticket_resolved_at_consistent CHECK ((status = 'resolved') = (resolved_at IS NOT NULL)), 
    CONSTRAINT ck_ticket_description_not_blank CHECK (btrim(description) <> ''), 
    CONSTRAINT fk_ticket_assigned_engineer_id_app_user FOREIGN KEY(assigned_engineer_id) REFERENCES app_user (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_ticket_firmware_release_id_firmware_release FOREIGN KEY(firmware_release_id) REFERENCES firmware_release (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_ticket_source_article_id_knowledge_article FOREIGN KEY(source_article_id) REFERENCES knowledge_article (id) ON DELETE SET NULL, 
    CONSTRAINT fk_ticket_source_node_id_decision_tree_node FOREIGN KEY(source_node_id) REFERENCES decision_tree_node (id) ON DELETE SET NULL, 
    CONSTRAINT fk_ticket_vehicle_id_vehicle FOREIGN KEY(vehicle_id) REFERENCES vehicle (id) ON DELETE RESTRICT
);

CREATE INDEX ix_ticket_assigned_engineer_id ON ticket (assigned_engineer_id);

CREATE INDEX ix_ticket_firmware_release_id ON ticket (firmware_release_id);

CREATE INDEX ix_ticket_source_article_id ON ticket (source_article_id);

CREATE INDEX ix_ticket_source_node_id ON ticket (source_node_id);

CREATE INDEX ix_ticket_status_sla_due_at ON ticket (status, sla_due_at);

CREATE INDEX ix_ticket_vehicle_id ON ticket (vehicle_id);

CREATE TABLE maintenance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    vehicle_id BIGINT NOT NULL, 
    aggregate_type_id BIGINT, 
    performed_by_user_id BIGINT, 
    ticket_id BIGINT, 
    performed_at DATE NOT NULL, 
    mileage_at_service INTEGER NOT NULL, 
    description VARCHAR(255), 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_maintenance_record PRIMARY KEY (id), 
    CONSTRAINT ck_maintenance_record_subject_present CHECK (aggregate_type_id IS NOT NULL OR description IS NOT NULL), 
    CONSTRAINT ck_maintenance_record_mileage_at_service_non_negative CHECK (mileage_at_service >= 0), 
    CONSTRAINT fk_maintenance_record_aggregate_type_id_aggregate_type FOREIGN KEY(aggregate_type_id) REFERENCES aggregate_type (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_maintenance_record_performed_by_user_id_app_user FOREIGN KEY(performed_by_user_id) REFERENCES app_user (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_maintenance_record_ticket_id_ticket FOREIGN KEY(ticket_id) REFERENCES ticket (id) ON DELETE SET NULL, 
    CONSTRAINT fk_maintenance_record_vehicle_id_vehicle FOREIGN KEY(vehicle_id) REFERENCES vehicle (id) ON DELETE RESTRICT
);

CREATE INDEX ix_maintenance_record_aggregate_type_id ON maintenance_record (aggregate_type_id);

CREATE INDEX ix_maintenance_record_performed_by_user_id ON maintenance_record (performed_by_user_id);

CREATE INDEX ix_maintenance_record_ticket_id ON maintenance_record (ticket_id);

CREATE INDEX ix_maintenance_record_vehicle_id ON maintenance_record (vehicle_id);

CREATE TABLE ticket_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    ticket_id BIGINT NOT NULL, 
    author_id BIGINT NOT NULL, 
    body TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_ticket_message PRIMARY KEY (id), 
    CONSTRAINT ck_ticket_message_body_not_blank CHECK (btrim(body) <> ''), 
    CONSTRAINT fk_ticket_message_author_id_app_user FOREIGN KEY(author_id) REFERENCES app_user (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_ticket_message_ticket_id_ticket FOREIGN KEY(ticket_id) REFERENCES ticket (id) ON DELETE RESTRICT, 
    CONSTRAINT uq_ticket_message_id_ticket_id UNIQUE (id, ticket_id)
);

CREATE INDEX ix_ticket_message_author_id ON ticket_message (author_id);

CREATE INDEX ix_ticket_message_ticket_id_created_at ON ticket_message (ticket_id, created_at);

CREATE TYPE attachment_type AS ENUM ('photo', 'video');

CREATE TABLE ticket_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    ticket_id BIGINT NOT NULL, 
    ticket_message_id BIGINT, 
    object_key VARCHAR(500) NOT NULL, 
    file_type attachment_type NOT NULL, 
    mime_type VARCHAR(100) NOT NULL, 
    size_bytes BIGINT NOT NULL, 
    uploaded_by_user_id BIGINT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_ticket_attachment PRIMARY KEY (id), 
    CONSTRAINT ck_ticket_attachment_mime_matches_type CHECK ((file_type = 'photo' AND mime_type LIKE 'image/%%') OR (file_type = 'video' AND mime_type LIKE 'video/%%')), 
    CONSTRAINT ck_ticket_attachment_size_positive CHECK (size_bytes > 0), 
    CONSTRAINT fk_ticket_attachment_ticket_id_ticket FOREIGN KEY(ticket_id) REFERENCES ticket (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_ticket_attachment_message_same_ticket FOREIGN KEY(ticket_message_id, ticket_id) REFERENCES ticket_message (id, ticket_id) ON DELETE RESTRICT, 
    CONSTRAINT fk_ticket_attachment_uploaded_by_user_id_app_user FOREIGN KEY(uploaded_by_user_id) REFERENCES app_user (id) ON DELETE RESTRICT, 
    CONSTRAINT uq_ticket_attachment_object_key UNIQUE (object_key)
);

CREATE INDEX ix_ticket_attachment_ticket_id ON ticket_attachment (ticket_id);

CREATE INDEX ix_ticket_attachment_ticket_message_id ON ticket_attachment (ticket_message_id);

CREATE INDEX ix_ticket_attachment_uploaded_by_user_id ON ticket_attachment (uploaded_by_user_id);

CREATE FUNCTION vehicle_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.vin IS DISTINCT FROM OLD.vin
               OR NEW.user_id IS DISTINCT FROM OLD.user_id
               OR NEW.vehicle_model_id IS DISTINCT FROM OLD.vehicle_model_id THEN
                RAISE EXCEPTION 'vehicle vin, user_id and vehicle_model_id are immutable'
                    USING ERRCODE = 'check_violation', CONSTRAINT = 'vehicle_identity_immutable';
            END IF;
            IF NEW.mileage < OLD.mileage THEN
                RAISE EXCEPTION 'vehicle mileage cannot decrease'
                    USING ERRCODE = 'check_violation', CONSTRAINT = 'vehicle_mileage_monotonic';
            END IF;
            RETURN NEW;
        END;
        $$;

CREATE TRIGGER trg_vehicle_guard BEFORE UPDATE ON vehicle FOR EACH ROW EXECUTE FUNCTION vehicle_guard();

INSERT INTO alembic_version (version_num) VALUES ('0001') RETURNING alembic_version.version_num;

-- Running upgrade 0001 -> 0002

INSERT INTO aggregate_type (code, name) VALUES ('engine_oil', 'Масло двигателя');

INSERT INTO aggregate_type (code, name) VALUES ('oil_filter', 'Масляный фильтр');

INSERT INTO aggregate_type (code, name) VALUES ('air_filter', 'Воздушный фильтр');

INSERT INTO aggregate_type (code, name) VALUES ('cabin_filter', 'Салонный фильтр');

INSERT INTO aggregate_type (code, name) VALUES ('gearbox_oil', 'Масло редуктора');

INSERT INTO aggregate_type (code, name) VALUES ('ac_refrigerant', 'Фреон кондиционера');

UPDATE alembic_version SET version_num='0002' WHERE alembic_version.version_num = '0001';

-- Running upgrade 0002 -> 0003

CREATE INDEX ix_maintenance_regulation_vehicle_model_id ON maintenance_regulation (vehicle_model_id);

UPDATE alembic_version SET version_num='0003' WHERE alembic_version.version_num = '0002';

COMMIT;

